set hive.execution.engine=tez;
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.exec.dynamic.partition=true;

MSCK REPAIR TABLE rawdb.xchannel_xbrand_visits;

create database if not exists testdb;
DROP VIEW if EXISTS testdb.test_visits;
CREATE VIEW if not exists testdb.test_visits PARTITIONED ON(groupkeydate) AS
SELECT
    Source,
    customerKey_RAW,
	customerKey,
	customerKey_INT,
	customerBrand,
	gender,
	YearOfBirth,
	age,
	ageBand,
	isBarredRetail,
	isBarredOnline,
	IsSelfExclude,
	CRMEmailOptInRetail,
	CRMEmailOptInOnline,
	CRMPostalOptInRetail,
	CRMPostalOptInOnline,
	CRMSMSOptInRetail,
	CRMSMSOptInOnline,
	CRMTelephoneOptInRetail,
	CRMTelephoneOptInOnline,
	IsVIPRetail,
	VIPLevelRetail,
	IsVIPOnline,
	VIPLevelOnline,
	venueCode,
	venueDesc,
	venueAddress1,
	venueCity,
	venuePostcode,
	venueLat,
	venueLong,
	venueAreaDesc,
	venueBrandDesc,
	venueChannelDesc,
	dayId,
	from_utc_timestamp(UNIX_TIMESTAMP(dayDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as dayDateTime,
	MarkDayName,
	MarkDayOfMonth,
	MarkDayOfQuarter,
	MarkDayOfHalf,
	MarkDayOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(MarkMonthDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as MarkMonthDateTime,
	MarkMonth,
	MarkMonthOfQuarter,
	MarkMonthOfHalf,
	MarkMonthOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(MarkQuarterDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as MarkQuarterDateTime,
	MarkQuarter,
	MarkQuarterOfHalf,
	MarkQuarterOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(MarkHalfDateTime , "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as MarkHalfDateTime,
	MarkHalf,
	MarkHalfOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(MarkYearfDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as MarkYearfDateTime,
	MarkYear,
	FiscDayName,
	FiscDayOfWeek,
	FiscDayOfPeriod,
	FiscDayOfQuarter,
	FiscDayOfHalf,
	FiscDayOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(FiscWeekDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as FiscWeekDateTime,
	FiscWeek,
	FiscWeekOfPeriod,
	FiscWeekOfQuarter,
	FiscWeekOfHalf,
	FiscWeekOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(FiscPeriodDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as FiscPeriodDateTime,
	FiscPeriod,
	FiscPeriodOfQuarter,
	FiscPeriodOfHalf,
	FiscPeriodOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(FiscQuarterDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as FiscQuarterDateTime,
	FiscQuarter,
	FiscQuarterOfHalf,
	FiscQuarterOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(FiscHalfDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as FiscHalfDateTime,
	FiscHalf,
	FiscHalfOfYear,
	from_utc_timestamp(UNIX_TIMESTAMP(FiscYearfDateTime, "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'")*1000,'GMT') as FiscYearfDateTime,
	FiscYear,
	sessCode,
	sessName,
	sessGroupName,
	dayId_Visit,
	visitHourOfDay,
	sec_venueAreaCode,
	sec_venueBrandCode,
	Customers_customerKey,
	FiscalCalendar_dayId,
	MarketCalendar_dayId,
	Sessions_sessCode,
	Venues_venueCode,
    GroupDate,
    GroupKeyDate
from rawdb.xchannel_xbrand_visits
Limit 5;